### ISSUE TITLE
오답

### ISSUE THREAD

**Issue by guijinSON** [jkc-ai/mwp-korean-data-2021#5]
```
class": "산술연산",
"question": "넓이가 48cm인 정사각형의 한 변의 길이는 몇 cm입니까?",
"answer": "12",
"equation": "48/4"
```

2 번 문제에 오답이 있어 알려드립니다. 한 변의 길이가 12cm 인 정사각형의 넓이는 48cm^2가 아닌 144cm^2입니다.

**Comment by qutrino** [comment]
감사합니다. 수정하였습니다.
2022년에 공개한 내용도 있으니 참고하시기 바랍니다. 
https://github.com/jkc-ai/mwp_kr_data
